import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.c
engine.c
gps.c
imu.c
sensor.c
ph.c
""")

if GetDepend(['RT_USING_DFS']):
    src += ['mnt.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
